[[workExperience]]
company = "Hitachi MGRM"
location = "Gurgaon, India"
role = "Data Analyst Intern"
duration = "Jan 2025 - Jul 2025"
responsibilities = [
    "Optimized Oracle SQL queries for analytics dashboards, reducing load times across all clients by 60%.",
    "Developed clustering logic for hierarchical data, enhancing high level attendance, enrollment, and employee analytics.",
    "Improved data visualization efficiency and accuracy for reporting for 200+ schools across Ladakh and Meghalaya and 20+ colleges across Bihar."
]

[[education]]
institution = "New York University"
location = "New York, NY"
degree = "M.S. Computer Science"
marks = "3.2"
duration = "Sep 2025 - Present"
coursework = [
    "Responsible AI and the Law",
    "Computer Vision",
    "Algorithms",
    "Neuroinformatics",
    "Machine Learning",
    "Data Visualization"
]

[[education]]
institution = "Vellore Institute of Technology, Vellore"
location = "Vellore, India"
degree = "B.Tech. Computer Science and Engineering"
marks = "8.49"
duration = "Sept 2021 - Jul 2025"
coursework = [
    "Predictive Analytics",
    "Machine Learning",
    "Artificial Intelligence",
    "Probability and Statistics",
    "Big Data Analytics",
    "Software Engineering",

]

  [[education.extracurriculars]]
  organization = "Indian Society For Technical Education"
  role = "Core Member"
  duration = "Mar 2022 - Jan 2023"
  details = [
    "Organized coding competitions and technical workshops for 500+ students",
    "Coordinated with a team of 10+ designers in designing Online Posters and Videos",
    "Invited industry speakers for tech talks and career guidance sessions"
  ]

  [[education.extracurriculars]]
  organization = "Indian Society For Technical Education"
  role = "Board Member"
  duration = "Jan 2023 - Apr 2024"
  details = [
    "Managed club operations and organized Video Editing workshops for 20+ students",
    "Oversaw a 40+ member team of video editors and designers, publishing content for the Chapter's publicity",
  ]

  [[education.extracurriculars]]
  organization = "Horizon: Indian Society for Technical Education"
  role = "Hackathon Organizer: Technica"
  duration = "Jan 2024 - Apr 2024"
  details = [
    "Coordinated a 48-hour hackathon with 300+ participants",
    "Secured sponsorships worth $2,000 from tech companies",
    "Managed logistics, judging panel, and prize distribution"
  ]

  [[education.extracurriculars]]
  organization = "Teach For Vellore"
  role = "Organizer"
  duration = "Sep 2023 - Dec 2023"
  details = [
    "Organised student teams that sparked inquisitiveness abot core science concepts to high schoolers at Williams Matriculation and Aatichuty Special School in Vellore.",
    "Conducted hands-on science experiments for high schoolers to demonstrate practical applications.",
    "Led non-profit outreach under ISTE-VIT to bridge the gap between academics and professional careers."
  ]

publications = []

[[projects]]
projectName = "Adversarial Debiasing Model"
technologies = "Pytorch"
role = ""
duration = "Dec 2025"
githubLink = "https://github.com/pxndey/csgy9223_project"
description = [
    "Engineered a custom Adversarial Debiasing Model from scratch to mitigate algorithmic bias in a diabetes dataset.",
    "Maintained high performance with 96.7% Accuracy, while achieving strong calibration parity across 5 racial groups.",
    "Reduced Maximum False Negative Rate disparity across 5 racial groups by 20%, ensuring equitable distribution across protected demographics."
]

[[projects]]
projectName = "GeoGuesser"
technologies = "StreetCLIP, HPC, Computer Vision"
role = ""
duration = "Dec 2025"
githubLink = "https://github.com/pxndey/csgy6643_p4"
description = [
    "Fine-tuned a StreetCLIP backbone on an HPC cluster to process over 329,000 multi-view images across 33 US states.",
    "Implemented a custom four-directional feature aggregation pipeline, maximizing spatial context for State Classification.",
    "Engineered a dual-target Computer Vision model achieving 88.9% accuracy on a 16,495-sample test set."
]

[[projects]]
projectName = "Parkinson's Disease Detection"
technologies = "TensorFlow"
role = ""
duration = "Nov 2024"
githubLink = "https://github.com/pxndey/parkinsons"
description = [
    "Developed novel dual ResNet152 architecture achieving 95.2% accuracy on spiral drawings and 90.4% on wave patterns.",
    "Implemented transfer learning with zero-training embedding method, achieving 100% precision on key datasets.",
    "Developed under the Guidance of Dr Sridhar Raj S (VIT)"
]

[[projects]]
projectName = "Engine RUL Prediction"
technologies = "RNN, Tensorflow"
role = ""
duration = "Nov 2024"
githubLink = "https://github.com/pxndey/engine_RUL"
description = [
    "Developed RNN model for aircraft engine lifetime prediction, achieving 31.6% better RMSE than existing literature.",
    "Engineered novel regression features and processed 20,000+ entries from NASA-CMAPSS time series dataset.",
    "Implemented complete ML pipeline including data preprocessing, model training and evaluation."
]

[[projects]]
projectName = "Research Paper Recommender"
technologies = "Graph Citation Networks, DeepWalk, Sentence-BERT"
role = ""
duration = "Nov 2024"
githubLink = "https://github.com/pxndey/rprs"
description = [
    "Used graph citation networks to model relationships between research papers.",
    "Employed DeepWalk and Sentence-BERT for vector representation and semantic similarity.",
    "Developed under the guidance of Dr Athira K (VIT)"
]

[[projects]]
projectName = "DRS"
technologies = "Go"
role = ""
duration = "Nov 2024"
githubLink = "https://github.com/pxndey/drs"
description = [
    "Command Line Tool to Show F1 Championship data",
    "Fetch Driver/Constructor Standings for any year, all within the terminal",
    "Display Historical Race Data and standings for any year"
]
