[[item]]
primary_color = "#212121"
accent_color  = "#FD4BC7"

[[item]]
primary_color = "#212121"
accent_color  = "#DC0000"

[[item]]
primary_color = "#333333"
accent_color  = "#00D2BE"

[[item]]
primary_color = "#212121"
accent_color  = "#FF8700"

[[item]]
primary_color = "#212121"
accent_color  = "#238c46"

[[item]]
primary_color = "#212121"
accent_color  = "#006BC1"

[[item]]
primary_color = "#0f0f0f"
accent_color  = "#1868DB"

[[item]]
primary_color = "#212121"
accent_color  = "#E10600"

[[item]]
primary_color = "#212121"
accent_color  = "#BB0A30"

[[item]]
primary_color = "#212121"
accent_color  = "#A00F2F"
