import * as TOML from 'toml'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const tomlPath = join(process.cwd(), 'portfolio-data.toml')
const outputPath = join(process.cwd(), 'src', 'data', 'portfolioData.generated.ts')

const tomlContent = readFileSync(tomlPath, 'utf-8')
const portfolioData = TOML.parse(tomlContent)

const tsContent = `// Auto-generated from portfolio-data.toml
// Do not edit this file directly - edit portfolio-data.toml instead

const portfolioData = ${JSON.stringify(portfolioData, null, 2)} as const

export default portfolioData
`

writeFileSync(outputPath, tsContent, 'utf-8')
console.log('✓ Generated portfolioData.generated.ts from portfolio-data.toml')
