import * as TOML from 'toml'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const tomlPath = join(process.cwd(), 'themes.toml')
const outputPath = join(process.cwd(), 'src', 'data', 'themes.generated.ts')

const tomlContent = readFileSync(tomlPath, 'utf-8')
const themesData = TOML.parse(tomlContent)

const tsContent = `// Auto-generated from themes.toml
// Do not edit this file directly - edit themes.toml instead

const themes = ${JSON.stringify(themesData, null, 2)} as const

export default themes
`

writeFileSync(outputPath, tsContent, 'utf-8')
console.log('✓ Generated themes.generated.ts from themes.toml')
