// Auto-generated from themes.toml
// Do not edit this file directly - edit themes.toml instead

const themes = {
  "item": [
    {
      "primary_color": "#212121",
      "accent_color": "#1D3BB0"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#DC0000"
    },
    {
      "primary_color": "#333333",
      "accent_color": "#00D2BE"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#FF8700"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#238c46"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#006BC1"
    },
    {
      "primary_color": "#0f0f0f",
      "accent_color": "#1868DB"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#E10600"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#BB0A30"
    },
    {
      "primary_color": "#212121",
      "accent_color": "#A00F2F"
    }
  ]
} as const

export default themes
